
# compiler
CXX	= gcc


# .o files
OFILES = s
# target name
TARGET	= output.o

INCLUDES = 
#LIBS
LIBS =  -lm

SRCS = main.c

# compile
all:	#$(OFILES)
	$(CXX) $(INCLUDES) $(EXTRA_CFLAGS) -o $(TARGET) $(SRCS) $(LIBS)
